# Generated by Django 4.2.3 on 2023-07-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='pop_singer_slug_46042c_idx')],
            },
        ),
    ]
